### ISSUE TITLE
Sara - Set up App locally

### ISSUE THREAD

**Issue by saradotlog** [OurTimeForTech/shiftwork#11]

**Comment by saradotlog** [comment]
Set up finished. 
I had to install Yarn, Ruby, Rails and Postgresql.
I installed the latest version of Ruby (3.0.0) so when I tried to run rails I had the 'your Ruby version is 3.0.0, but your Gemfile specified 2.7.1' error. Installed rbenv, tried to install 2.2.5 but gave me some error related to macOS Catalina. Tried 2.7.1 and even tho when I typed 'ruby -v' in the console it appeared 2.7.1 correctly, when I tried to run rails I had the same 'your Ruby version is 3.0.0...' again. So I ended up uninstalling Ruby and installing the version 2.7.1 directly and everything works fine now.

**Comment by msarit** [comment]
Hi @saradotlog! 👋🏾  Wonderful! Great job documenting your setup process! 🎉
