### ISSUE TITLE
Carla - Set app up locally

### ISSUE THREAD

**Issue by cclics** [OurTimeForTech/shiftwork#14]

**Comment by msarit** [comment]
Hi @cclics! 👋🏾  Did you get this done successfully?

**Comment by cclics** [comment]
Hi @msarit, I have installed Ruby vs 2.6.3, sqlite vs 3.22.2, node v14.15.3, yarn 1.22.10, rails 6.1.3. Postgres vs 13.2 is up and running.
But I'm facing some problems trying (on Instructions nr 5) to run db-setup because the Ruby and Gemfile are not compatible, I got this Error message "Ruby version is 2.6.3, but your Gemfile specified 2.7.1"
I also noticed that I had another git account on my computer different from account I'm using for the Collab Project.

**Comment by msarit** [comment]
@cclics which ruby version manager do you use? If you have (or can download) `rbenv`, do the following:
- Run `rbenv versions` to see which ruby versions you already have. If you do NOT see 2.7.1 in the list, then run `rbenv install 2.7.1`.
- Then within the project folder, run `rbenv local 2.7.1`.
- Lastly, run `bundle install`.

This is a cool rbenv cheatsheet I use: https://devhints.io/rbenv

Let me know if you are still having trouble. And for future reference, ask for help early! ❤️  Once we start building the app, things could move really quickly and you don't want to feel left behind 😄

**Comment by cclics** [comment]
@msarit thank you!
I noticed I had updated ruby to version 3.0
**corcovado@Corcovados-MBP shiftwork % bundle install                        
Your Ruby version is 3.0.0, but your Gemfile specified 2.7.1**
When I'm trying to running bundle install 
**corcovado@Corcovados-MBP shiftwork % bundle install                        
Your Ruby version is 3.0.0, but your Gemfile specified 2.7.1
corcovado@Corcovados-MBP shiftwork %** 
Now Ruby 3.0 is not compatible with Gemfile 2.7.1

Have an idea how can I solve it?

**Comment by cclics** [comment]
I recovered the earlier version but I got same issue:
**corcovado@Corcovados-MBP shiftwork % bundle install
Your Ruby version is 2.6.3, but your Gemfile specified 2.7.1
corcovado@Corcovados-MBP shiftwork %**

**Comment by saradotlog** [comment]
Hi @cclics 
I don't know if you will find this helpful, but I had the same issue as you. I tried to change version with rbenv but wasn't able to make it work (If I ran ruby -v it told me 2.7.1 correctly but trying to run db-setup was telling me the same "Your Ruby version is....") so finally the only thing that worked for me was uninstall ruby completely and install directly the version 2.7.1.

**Comment by msarit** [comment]
Hey Carla, let me read

**Comment by msarit** [comment]
Alright, run `rbenv version` what do you see?

**Comment by cclics** [comment]
@saradotlog thanks, I think it seems to be the best option. I think I'll go for it.
@msarit: I got this:
**corcovado@Corcovados-MBP ~ % rbenv versions**
* system (set by /Users/corcovado/.rbenv/version)
  2.6.3
  2.7.1
**corcovado@Corcovados-MBP ~ % rbenv version**
system (set by /Users/corcovado/.rbenv/version)

**Comment by msarit** [comment]
okay so it looks like you have version 2.7.1 installed

I think I see the problem: you are NOT in your project's folder (I see your path as `corcovado@Corcovados-MBP ~ `)

have you forked the ShiftWork project and cloned it to your laptop?

**Comment by cclics** [comment]
yes, I have:
**corcovado@Corcovados-MBP shiftwork % rbenv version**
2.6.3 (set by /Users/corcovado/development/collab/shiftwork/.ruby-version)
**corcovado@Corcovados-MBP shiftwork % rbenv versions**
  system
* 2.6.3 (set by /Users/corcovado/development/collab/shiftwork/.ruby-version)
  2.7.1
**corcovado@Corcovados-MBP shiftwork % ls**
Gemfile				log
Gemfile.lock			package.json
README.md			postcss.config.js
Rakefile			public
app				pull_request_template.md
babel.config.js			storage
bin				test
config				tmp
config.ru			vendor
db				yarn.lock
lib

**Comment by msarit** [comment]
Ok good. Now in THIS folder, run `rbenv local 2.7.1`
Then run `bundle install`
Tell me what you see

**Comment by cclics** [comment]
I got the same error:
corcovado@Corcovados-MBP shiftwork % pwd
/Users/corcovado/development/collab/shiftwork
corcovado@Corcovados-MBP shiftwork % rbenv local 2.7.1
corcovado@Corcovados-MBP shiftwork % bundle install
**Your Ruby version is 2.6.3, but your Gemfile specified 2.7.1**
corcovado@Corcovados-MBP shiftwork %

**Comment by msarit** [comment]
did you run `rbenv local 2.7.1` within the folder first?

**Comment by msarit** [comment]
after running `rbenv local 2.7.1`, run `rbenv version` and tell me what you see

**Comment by cclics** [comment]
This:
**corcovado@Corcovados-MBP shiftwork % rbenv local 2.7.1**
**corcovado@Corcovados-MBP shiftwork % rbenv version**
2.7.1 (set by /Users/corcovado/development/collab/shiftwork/.ruby-version)
corcovado@Corcovados-MBP shiftwork %

**Comment by msarit** [comment]
so it's showing the correct version set, but when you run `bundle install` it complains that the version is 2.6.3? This is weird

**Comment by msarit** [comment]
run this and tell me what you see: `cat ~/.bash_profile`

**Comment by cclics** [comment]
I ran bundle install successfully. After that I was trying to  run db:setup then I got this error. 
**corcovado@Corcovados-MBP shiftwork % rails db:setup**                   
Ignoring racc-1.5.2 because its extensions are not built. Try: gem pristine racc --version 1.5.2
Ignoring racc-1.5.2 because its extensions are not built. Try: gem pristine racc --version 1.5.2
Ignoring racc-1.5.2 because its extensions are not built. Try: gem pristine racc --version 1.5.2
Ignoring racc-1.5.2 because its extensions are not built. Try: gem pristine racc --version 1.5.2
Ignoring racc-1.5.2 because its extensions are not built. Try: gem pristine racc --version 1.5.2
Ignoring racc-1.5.2 because its extensions are not built. Try: gem pristine racc --version 1.5.2
Your Ruby version is 2.6.3, but your Gemfile specified 2.7.1

I'm using Mac with BigSur,  the file ~/.zshrc looks like:
 **corcovado@Corcovados-MBP shiftwork % cat ~/.zshrc**
export JAVA_HOME=$(/usr/libexec/java_home)
export TOOLS_HOME=/Users/corcovado/development/tools
export ANDROID_HOME=/Users/corcovado/Library/Android/sdk
export M2_HOME=$TOOLS_HOME/apache-maven-3.6.3
export GEM_HOME=/Users/corcovado/.gem
export PATH=$PATH:$M2_HOME/bin
export PATH=$PATH:$TOOLS_HOME/flutter/bin
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$GEM_HOME/bin
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

**Comment by cclics** [comment]
I got this error trying to run rails db:setup. I also can't start postgres and pgAdmin

```
**corcovado@Corcovados-MBP shiftwork % rails db:setup**
rails aborted!

LoadError: dlopen(/Users/corcovado/.gem/gems/pg-1.2.3/lib/pg_ext.bundle, 9): **Library not loaded:** /usr/local/opt/postgresql/lib/libpq.5.dylib
  Referenced from: /Users/corcovado/.gem/gems/pg-1.2.3/lib/pg_ext.bundle

```
