### ISSUE TITLE
NEW: Install Devise Gem (old: Create table for user accounts)

### ISSUE THREAD

**Issue by saradotlog** [OurTimeForTech/shiftwork#20]
Fields:
- ID (Int, Auto Increment, not null, primary key)
- Username (varchar(100), not null) 
- Email (varchar (256), not null)
- Password (varchar(20), not null, MD5 encryption) 
- Linked ID (business or workers)?? As the user ID will be unique, we can reference the user from the workers/business tables. So if we store the user ID in those tables, once a person logs in we can get the user ID by the username/password and retrieve the info from the workers/business tables based on that u.id with a JOIN query
- Type of user (Business/worker) This might be an easier way to solve the problem, as we will have directly the type of user and their ID and can go to the correct table to get the info

In order to manage the users, we are using the Devise Gem. I've seen different tutorials but this has a bit of an explanation at the beginning that can be helpful:
https://medium.com/@byron.skoutaris/how-to-set-up-devise-gem-a8610be46d83
It also explains how to install it and configure it.
To sumarise:

- Open up your Gemfile and add this line `gem 'devise'`
- Run `bundle install` to install the gem
- Restart your rails server
- Run `rails g devise:install`
- Open up `config/environments/development.rb` and add:
`config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }` before the end keyword.
- Open up `app/views/layouts/application.html.erb` and add:
`<% if notice %> <p class="alert alert-success"><%= notice %></p> <% end %>`
 ` <% if alert %> <p class="alert alert-danger"><%= alert %></p> <% end %>`
right above
`<%= yield %>`
- Open up `app/views/ideas/show.html.erb` and remove the line that says:
`<p id="notice"><%= notice%></p>`
Do the same for `app/views/comments/show.html.erb`
- Setup the User model:
`rails g devise` 
`rails db:migrate`

That would be the installation. Then we can create the first user and add sign-up and login links. It is also explained in the article.

**Comment by msarit** [comment]
@saradotlog Hi Sara! I changed the label on this back to "In Planning", as I have a few questions:

> Username (varchar(50), not null) (the username can be the email address, otherwise another field for the email would be needed)

You mention that `username` can be an actual username (in the which case, we would need separate fields for username and email address), or the email can serve as the username. What is the team's consensus on this?
@Timilehin08 @ncbui @GabrielleEaston @cclics

**Comment by msarit** [comment]
@drippdropp Hey Daniel, could you weigh in on the fields `type_of_user` and `linked_id`? I'm not sure we hashed them out during last week's sprint planning

**Comment by GabrielleEaston** [comment]
If I understood correctly, I think it will be easier if username == email (the email can serve as the username). Thinking from the users' perspectives, always easier to remember the email you signed up with than the username you picked for that particular application.

**Comment by saradotlog** [comment]
Maybe having a unique username can help to appear across the website without having to give away personal info like email or name?
I just read @GabrielleEaston comment and she is also right, I generally prefer to have only the email as a user. We can also allow to log in with both, email or username, so they don't have to remember it.

**Comment by msarit** [comment]
Great points @saradotlog @GabrielleEaston! I think for logging in, let's go with `email` (like Gabrielle said). But let us also have a `username` attribute with which to have profile pages like `shiftwork.herokuapp.com/username`.

@saradotlog please make the necessary changes to the Issue Description

**Comment by msarit** [comment]
Hello team, for user accounts, I am thinking we should use a ruby gem called Devise. I'm discussing with Daniel and will update this ticket based on what we decide.

**Comment by msarit** [comment]
@saradotlog Hey Sara! Would you please do some high-level research on installing the Devise gem, and update this issue with those instructions? Once you update the issue, I will adopt it. 👍🏾

**Comment by saradotlog** [comment]
@msarit Issue updated!! :)
