### ISSUE TITLE
Create Workers table

### ISSUE THREAD

**Issue by ncbui** [OurTimeForTech/shiftwork#23]
Will be mapped to Shifts and Work-Slots tables:
Workers sign up for Shifts
Workers own Work-Slots

Attributes:
worker_id      SERIAL PRIMARY KEY
first_name    VARCHAR(50) NOT NULL
last_name     VARCHAR(50) NOT NULL
city                VARCHAR(50) NOT NULL
state             CHAR(2) NOT NULL
user_id          INT REFERENCES worker(id)

This issue may be blocked by issue #20, create user tables (need to know the field name for ids)

**Implementation** 
According to Rails convention, model names are singular (eg Business) while Controller names are pluralized (eg Businesses). However, "businesses" is a mouthful and easy to misspell. So I propose we use Organization, which Rails will pluralize to Organizations and is more straightforward.

This symbol ⏩ signifies an action you must take.

⏩ Syntax to generate models, controllers, data migration and views for Organization:

`bin/rails generate scaffold Worker worker_firstname:string worker_lastname:string worker_city:string worker_state:string user:references`

Note: the rails generate scaffold command does A LOT under the hood. This command generates the model, controllers, views and data migration for the indicated entity (Organization in this case). After running this command, you should see the following output, which shows all the files created:

Running via Spring preloader in process 17112

>       invoke  active_record
>       create    db/migrate/20210309211309_create_organizations.rb
>       create    app/models/organization.rb
>       invoke    test_unit
>       create      test/models/organization_test.rb
>       create      test/fixtures/organizations.yml
>       invoke  resource_route
>        route    resources :organizations
>       invoke  scaffold_controller
>       create    app/controllers/organizations_controller.rb
>       invoke    erb
>       create      app/views/organizations
>       create      app/views/organizations/index.html.erb
>       create      app/views/organizations/edit.html.erb
>       create      app/views/organizations/show.html.erb
>       create      app/views/organizations/new.html.erb
>       create      app/views/organizations/_form.html.erb
>       invoke    test_unit
>       create      test/controllers/organizations_controller_test.rb
>       create      test/system/organizations_test.rb
>       invoke    helper
>       create      app/helpers/organizations_helper.rb
>       invoke      test_unit
>       invoke    jbuilder
>       create      app/views/organizations/index.json.jbuilder
>       create      app/views/organizations/show.json.jbuilder
>       create      app/views/organizations/_organization.json.jbuilder
>       invoke  assets
>       invoke    scss
>       create      app/assets/stylesheets/organizations.scss
>       invoke  scss
>       create    app/assets/stylesheets/scaffolds.scss

      
⏩ Then, run database migrations (basically, executing this file db/migrate/20210309211309_create_organizations.rb - your timestamp will be different):

`bin/rails db:migrate`

**Comment by msarit** [comment]
Great work @ncbui! Would you please leave some notes on if this Issue is expected to be blocked by any other issues, or will itself be a blocker for other issues?

**Comment by msarit** [comment]
This issue is still "In Planning" because I need to figure out with Daniel how we'll integrate the Users table/model with the Workers Table/model. Just FYI.

**Comment by ncbui** [comment]
Thank you for the update. I've updated the description with notes that you've shared

**Comment by msarit** [comment]
Completed in version 2 - closing this issue
