### ISSUE TITLE
Create Shifts table

### ISSUE THREAD

**Issue by GabrielleEaston** [OurTimeForTech/shiftwork#24]
#### Attributes:
ID :primary_key NOT NULL 
Organization_ID  References organization_id that created the shift NOT NULL
Worker_ID References worker_id (the id of the Worker filling the shift)
Status :Boolean (filled or unfilled)
Role_name :string
Date :date
Start_time :time
End_time :time
Pay_rate_per_hour :integer

This Issue may be blocked by the Organizations Table Issue (will link to it once its issue is created).

#### Implementation:
This symbol ⏩ signifies an action you must take.

⏩ Syntax to generate models, controllers, data migration and views for Shift:
```
bin/rails generate scaffold Shift shift_status:boolean role_name:string shift_start:datetime shift_end:datetime shift_pay:integer
```
**Note**: the rails generate scaffold command does A LOT under the hood. This command generates the model, controllers, views and data migration for the indicated entity (Shift in this case). 
**Note**: we have left some fields out, like Organization_ID and Worker_ID. These can be added later.

⏩ Finally, run database migrations (basically, executing this file db/migrate/20210309211309_create_shifts.rb - your timestamp will be different):
```
bin/rails db:migrate
```

**Comment by msarit** [comment]
Awesome work @GabrielleEaston! Would you please leave some notes on if this Issue is expected to be blocked by any other issues, or will itself be a blocker for other issues?

**Comment by GabrielleEaston** [comment]
I think this issue is expected to be blocked by Businesses. 
Businesses own Shifts
Shifts are associated with Workers as well. I don't think Workers will be a blocker for Shifts.
Shifts are not expected to be a blocker for other issues.
Hopefully, I got it right!
