### ISSUE TITLE
Create Work-Slots table

### ISSUE THREAD

**Issue by cclics** [OurTimeForTech/shiftwork#25]
Table-name: WORK_SLOTS
Atributes: 

- ID (primary key; can’t be blank) - datatype integer, auto-incremented - not null
- Worker ID (the id of the worker that creates the work-slot; can’t be empty) - not null
- Shift ID (the id of the shift that the work-slot coincide with; can be empty)  - optional
- Date - datatype: TIMESTAMP is YYYY-MM-DD - not null
- Start Time - datatype: TIMESTAMP is YYYY-MM-DD HH:MM:SS  - not null
- End Time - datatype: TIMESTAMP is YYYY-MM-DD HH:MM:SS - not null

This issue may be blocked by Workers Table. [Issue#23](https://github.com/OurTimeForTech/shiftwork/issues/23#issue-823401249)

**Comment by msarit** [comment]
This is great @cclics! Would you please leave some notes on if this Issue is expected to be blocked by any other issues, or will itself be a blocker for other issues?

**Comment by msarit** [comment]
Will be deliberated as part of V2 - closing this issue
