### ISSUE TITLE
Create table for Organizations (old: create table for businesses)

### ISSUE THREAD

**Issue by Timilehin08** [OurTimeForTech/shiftwork#26]
#### Attributes:
ID (primary key, can’t be empty): datatype integer
Business Name: string
Business Address: string
City: string
State :string

#### Associations:
Businesses own shifts

#### Implementation:
According to Rails convention, model names are singular (eg `Business`) while Controller names are pluralized (eg `Businesses`). However, "businesses" is a mouthful and easy to misspell. So I propose we use `Organization`, which Rails will pluralize to `Organizations` and is more straightforward.

This symbol ⏩ signifies an action you must take.

⏩ Syntax to generate models, controllers, data migration and views for Organization:
```
bin/rails generate scaffold Organization org_name:string org_address:string org_city:string org_state:string
```

Note: the `rails generate scaffold` command does A LOT under the hood. This command generates the model, controllers, views and data migration for the indicated entity (`Organization` in this case). After running this command, you should see the following output, which shows all the files created:
```
Running via Spring preloader in process 17112
      invoke  active_record
      create    db/migrate/20210309211309_create_organizations.rb
      create    app/models/organization.rb
      invoke    test_unit
      create      test/models/organization_test.rb
      create      test/fixtures/organizations.yml
      invoke  resource_route
       route    resources :organizations
      invoke  scaffold_controller
      create    app/controllers/organizations_controller.rb
      invoke    erb
      create      app/views/organizations
      create      app/views/organizations/index.html.erb
      create      app/views/organizations/edit.html.erb
      create      app/views/organizations/show.html.erb
      create      app/views/organizations/new.html.erb
      create      app/views/organizations/_form.html.erb
      invoke    test_unit
      create      test/controllers/organizations_controller_test.rb
      create      test/system/organizations_test.rb
      invoke    helper
      create      app/helpers/organizations_helper.rb
      invoke      test_unit
      invoke    jbuilder
      create      app/views/organizations/index.json.jbuilder
      create      app/views/organizations/show.json.jbuilder
      create      app/views/organizations/_organization.json.jbuilder
      invoke  assets
      invoke    scss
      create      app/assets/stylesheets/organizations.scss
      invoke  scss
      create    app/assets/stylesheets/scaffolds.scss
``` 

⏩ Then, run database migrations (basically, executing this file `db/migrate/20210309211309_create_organizations.rb` - your timestamp will be different):
```
bin/rails db:migrate
```

**Comment by msarit** [comment]
Hello team! I have updated the description for this Issue and included the syntax for getting this issue done. This issue is ready to be worked on! 🎉 

@ncbui @GabrielleEaston @Timilehin08 @cclics @saradotlog

**Comment by ncbui** [comment]
PR for the blocking issue (#34 ) is currently at the approved stage. Assigning this to myself to work on this week.

**Comment by msarit** [comment]
No longer Blocked - work away!
