### ISSUE TITLE
Install Bootstrap Gem

### ISSUE THREAD

**Issue by GabrielleEaston** [OurTimeForTech/shiftwork#28]
How to install the Bootstrap gem. Referencing the following resource>> https://www.rubydoc.info/gems/bootstrap/4.0.0
1. Add bootstrap to your Gemfile:
gem 'bootstrap', '~> 4.0.0'
* Ensure that sprockets-rails is at least v2.3.2.
2. run command >> bundle install and restart your server to make the files available through the pipeline.
3. Import Bootstrap styles in app/assets/stylesheets/application.scss:
@import "bootstrap";
**NOT SURE STEP 4 IS NECESSARY????????**
_4.Make sure the file has .scss extension (or .sass for Sass syntax). If you have just generated a new Rails app, it may come with a .css file instead. If this file exists, it will be served instead of Sass, so rename it:
$ mv app/assets/stylesheets/application.css app/assets/stylesheets/application.scss_
5. Bootstrap JavaScript depends on jQuery. If you're using Rails 5.1+, add the jquery-rails gem to your Gemfile:
 gem 'jquery-rails'
6.Bootstrap tooltips and popovers depend on popper.js for positioning. The bootstrap gem already depends on the popper_js gem.
Add Bootstrap dependencies and Bootstrap to your application.js file: 
//= require jquery3
//= require popper
//= require bootstrap-sprockets

**Comment by msarit** [comment]
@GabrielleEaston Hey! Nice job creating this issue. Would you please do the research on installing the gem, and include the instruction in this issue? You can high-level it - you don't have to be super-detailed 😄 

Once you do this, I will adopt this issue.

**Comment by GabrielleEaston** [comment]
@msarit Updated the issue! Not sure step 4 is NECESSARY since we are not using SASS.
