### ISSUE TITLE
Update constraints on shifts table

### ISSUE THREAD

**Issue by ncbui** [OurTimeForTech/shiftwork#37]
Add constraints to shifts table's field.

Currently: 
Shifts can be created without a role name or pay rate. 
Shifts can also be created with odd start/end times. For example, starting in October 2021 but ending in March 2021. Or starting at 3 March 2021 20:00:00  and ending 3 March 2021 10:00:00.

This issue is found while reviewing PR #33, but it is not blocked by and does not block other issues. 

**Implementation:**

Generate an empty migration `$ bin/rails generate migration AddConstraintsToShifts`

Alter the migration file to look like
```
class AddPartNumberToProducts < ActiveRecord::Migration[6.0]
  def change
    change_column_null :shifts, :role_name, false
    change_column_null :shifts, :shift_pay, false
    change_column_null :shifts, :shift_start, false
    change_column_null :shifts, :shift_end , false
  end
end
```
Then run 
```
bin/rails db:migrate
```

Alter the `app/models/shifts.rb` file to add a custom validation for shift_end column
```
class Shift < ApplicationRecord
    validates :role_name, :presence => true
    validates :shift_start, :presence => true
    validates :shift_end , :presence => true
    validates :shift_pay, :presence => true
  
   validate :end_date_after_start_date?

   def end_date_after_start_date?
       if shift_end < shift_start
          errors.add :shift_end, "shift must be after start date"
       end
    end

end
```

**Comment by ncbui** [comment]
Added implementation notes compiled from [x](https://guides.rubyonrails.org/active_record_validations.html#performing-custom-validations) [x](https://guides.rubyonrails.org/active_record_migrations.html) [x](https://stackoverflow.com/questions/33639833/validate-that-an-end-date-is-later-than-a-start-date-in-rails-4)

**Comment by msarit** [comment]
Closing this Issue in favor of V2
