### ISSUE TITLE
Add styles for login page

### ISSUE THREAD

**Issue by saradotlog** [OurTimeForTech/shiftwork#41]
Adding some basic styling to the login page with bootstrap (https://getbootstrap.com/docs/5.0/examples/).
The markup of the page http://localhost:3000/users/sign_in already matches the one of the wireframes (https://www.figma.com/file/WKz1DISMzfdRLOFrNOCEdW/Wireframe?node-id=0%3A1)

Blocked by Issue #28

**Comment by msarit** [comment]
Closing this Issue in favor of V2
