### ISSUE TITLE
Add markup for sign up page

### ISSUE THREAD

**Issue by saradotlog** [OurTimeForTech/shiftwork#42]
Add all the fields for the sign up page. 
I think we agreed on having first a form to add the email/password and a tick box to specify worker/business and after it another form with the rest of the sign up information. 
I think we can build the forms and add the style and functionality after it?

Needs the wireframes to be updated #29 but it is not necessarily a blocker

**Comment by msarit** [comment]
Hey @saradotlog let's hold off on this until we have the Worker and Work-Slots MVCs and tables completed 👍🏾

**Comment by msarit** [comment]
Closing this issue in favor of V2
