### ISSUE TITLE
Add association between Org and Users Models

### ISSUE THREAD

**Issue by ncbui** [OurTimeForTech/shiftwork#46]
Users own orgs

> $ bin/rails generate migration AddUsersToOrganizations user:references
> $ bin/rails db:migrate

This migration will create a user_id column with index as well as migration with file that looks like:

> class AddUsersToOrganizations < ActiveRecord::Migration[6.0]
>  def change
>    add_reference :organizations, :users, foreign_key: true
>  end
>end

**Comment by ncbui** [comment]
Added notes from the Rails official docs on [active record migrations](https://edgeguides.rubyonrails.org/active_record_migrations.html#creating-a-standalone-migration)

**Comment by msarit** [comment]
Holding off on adopting this issue, @ncbui, until the User-Org and User-Worker links are squared away 👍🏾

**Comment by msarit** [comment]
Closing this Issue in favor of V2
