### ISSUE TITLE
Add association between shifts and org tables

### ISSUE THREAD

**Issue by ncbui** [OurTimeForTech/shiftwork#52]
Orgs should own Shifts
When an org creates a shift, the shift should have a reference to the org that owns it. 

```
$ bin/rails generate migration AddOrganizationsToShifts organization:references
$ bin/rails db:migrate
```

This migration will create a user_id column to the shifts table with index as well as migration with file that looks like:

```
class AddOrganizationsToShifts < ActiveRecord::Migration[6.0]
  def change
    add_reference :shifts, :organizations, foreign_key: true
  end
end
```

**Comment by ncbui** [comment]
Added implementation notes from the Rails official docs on[ Active Record Migration](https://edgeguides.rubyonrails.org/active_record_migrations.html#creating-a-standalone-migration)

**Comment by msarit** [comment]
Holding off on adopting this issue, @ncbui, until the User-Org and User-Worker links are squared away 👍🏾

**Comment by msarit** [comment]
Closing this Issue in favor of V2
