### ISSUE TITLE
Timi - Set app up locally

### ISSUE THREAD

**Issue by Timilehin08** [OurTimeForTech/shiftwork#8]
Aim to have this done by Saturday

**Comment by Timilehin08** [comment]
I have ruby version 2.7.2 downloaded on my system. However when I 'rails db-setup', it popped up an error saying 'ruby 2.7.2 is downloaded but GEM file specified 2.7.1'. Checked Stackoverflow for a solution and i was told to change the gem file to what is on my system which is '2.7.2' but this  is also going to lead me to changing some couple of other things in the GEM file.

**Comment by Timilehin08** [comment]
i don't know if this problem is peculiar to me as I am unable to download the version '2.7.1' that is in the GEM file from the web.

**Comment by msarit** [comment]
Hi @Timilehin08! 👋🏾  Are you still having issues?

**Comment by Timilehin08** [comment]
setup and running on my machine so i will close this now.
